### PR TITLE
filter out the rows that do have non-numbers

### PR DESCRIPTION
**Pull request by alexott**
rationale: in some cases, the database query (for example in Cassandra) doesn't allow to
filter out the null values, etc.  In this case current version shows error.

The proposed change just throw away that rows that have non-numbers

P.S. maybe we need to log that decision, need to be discussed

### CODE REVIEW

**Comment by alexott** [comment]
I've simplified the code to use `isNaN` function instead of comparison - don't know why it didn't work well for me at first try (I'm not JS dev :-)

**Comment by alexott** [comment]
I also have a question about general approach to that stuff - our product (DataStax Enterprise) uses WKT format for representing points, lines, and polygons - maybe it will be possible to somehow add support for it into the same extension? But it will require that we have UI to select either points, or lat/lon pairs... I know that some other databases use either pairs as strings, or WKT as well

I can try to add corresponding code if it's ok for you...

**Comment by myuwono** [comment]
Thanks, looks good. Yeah sounds great👍

**Comment by alexott** [comment]
Ok, let me play with code to make following change: either require that `lat`/`lon` fields are specified, or `point` field is specified (and inside that field support WKT & other formats, like, `num num`, `num,num`, ...)

**Pull request merged**
